import Header from "@/components/Header/Header";
import PostProvider from "./context/PostProvider";
import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css"
import { roboto, montserrat } from "@/fonts"

export const metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({ children }) {
return (
    <html lang="en">
        <body className={`${roboto.variable} ${montserrat.variable}`}>
            <Header />
            <main>
                <PostProvider>
                    {children}
                </PostProvider>
            </main>
        </body>
    </html>
);
}
